import { K } from "./kdls";

export interface FeatureData {
  id: string;
  label: string;
  icon: string;
  color: string;
  tagline: string;
  desc: string;
  stat: string;
  statLabel: string;
  detail: string;
  sec1Title: string;
  sec1Body: string;
  sec2Title: string;
  sec2Body: string;
  sec3Title: string;
  sec3Body: string;
  capabilities: string[];
  useCases: { title: string; desc: string }[];
}

export const FEATURES: FeatureData[] = [
  // ── 1. LTV Enrichment ─────────────────────────────────────
  {
    id: "ltv-enrichment",
    label: "LTV Enrichment",
    icon: "\u25CE",
    color: K.mint,
    tagline: "Turn $149 orders into $640 signals",
    desc: "Every conversion intercepted server-side. ML predicts 90-day LTV in <50ms. Platforms learn to find your real buyers \u2014 not just high first-order spenders.",
    stat: "4.29\u00D7",
    statLabel: "avg LTV uplift",
    detail: "Gradient boosting trained on your historical order and LTV data. R\u00B2 typically 0.87\u20130.94. Prediction in under 50ms. Sent to all platforms automatically.",
    sec1Title: "Server-Side Interception",
    sec1Body: "Every conversion is caught server-side before it reaches any ad platform. This gives you full control over what data your optimization algorithms see \u2014 ensuring they learn the right signals.",
    sec2Title: "ML-Powered LTV Prediction",
    sec2Body: "Our gradient boosting model analyzes 28 signal features \u2014 order value, product category, session behavior, device, time-of-day, and more \u2014 to predict 90-day lifetime value with R\u00B2 > 0.87. Predictions update in real-time as new data arrives.",
    sec3Title: "Cross-Platform Distribution",
    sec3Body: "The enriched LTV signal is simultaneously delivered to all 14 connected ad platforms via native CAPI integrations. Meta, Google, TikTok, LinkedIn, and more all receive the same high-quality signal.",
    capabilities: [
      "28-feature signal enrichment per conversion",
      "90-day LTV prediction with gradient boosting",
      "Sub-50ms prediction latency at P99",
      "Server-side conversion interception (CAPI)",
      "Simultaneous delivery to 14 ad platforms",
      "Real-time model retraining as new data arrives",
    ],
    useCases: [
      { title: "DTC Brands", desc: "Replace raw order values with predicted LTV so Meta optimizes for customer quality, not first-purchase revenue." },
      { title: "Subscription Services", desc: "Predict 90-day retention value at the moment of conversion and bid accordingly on high-LTV segments." },
      { title: "Marketplaces", desc: "Enrich every signup or listing with predicted platform GMV to acquire sellers with highest long-term value." },
    ],
  },

  // ── 2. CAPI & Signal Pipeline ─────────────────────────────
  {
    id: "capi-signal-pipeline",
    label: "CAPI & Signal Pipeline",
    icon: "\u25C9",
    color: K.teal,
    tagline: "Server-side conversions. Zero data loss.",
    desc: "Native CAPI integrations across 14 platforms. Every conversion captured server-side, enriched with LTV, fraud-scored, and delivered in under 100ms.",
    stat: "14",
    statLabel: "platform integrations",
    detail: "28-feature signal processing pipeline. SHA-256 idempotent deduplication. 4-tier LTV classification. P99 latency under 100ms end-to-end.",
    sec1Title: "Multi-Platform CAPI Gateway",
    sec1Body: "A single integration point for all 14 ad platforms. Connect Meta Conversions API, Google Ads, TikTok Events API, LinkedIn, Snap, Pinterest, and more through one unified gateway. No per-platform engineering needed.",
    sec2Title: "28-Feature Signal Engineering",
    sec2Body: "Each conversion is expanded into a 28-feature vector across 5 dimensions: Order History (7 features), Customer Behavior (6), Attribution Signals (5), Temporal Patterns (5), and Product Category (5). This rich signal gives ML models maximum predictive power.",
    sec3Title: "Idempotent Delivery",
    sec3Body: "SHA-256 dedup IDs prevent double-counting across all platforms. Retry with idempotency ensures delivery guarantees. P99 delivery latency under 100ms from event receipt to platform delivery.",
    capabilities: [
      "Native CAPI integrations for 14 platforms",
      "28-feature signal expansion per event",
      "Server-side event interception",
      "SHA-256 idempotent deduplication",
      "P99 latency under 100ms end-to-end",
      "4-tier LTV classification (high/mid/low/churn)",
    ],
    useCases: [
      { title: "High-Volume DTC", desc: "Capture every conversion without pixel loss. Server-side CAPI eliminates browser blocking and ad-blocker data loss." },
      { title: "Multi-Platform Advertisers", desc: "One integration point for all platforms. Enrich once, deliver everywhere. No per-platform engineering or maintenance." },
      { title: "Data Quality Teams", desc: "Full visibility into every signal. 28-feature enrichment ensures downstream ML models have the richest possible feature set." },
    ],
  },

  // ── 3. AI Agents ──────────────────────────────────────────
  {
    id: "ai-agents",
    label: "AI Agents",
    icon: "\u26A1",
    color: K.blue,
    tagline: "Autonomous bidding. Zero manual work.",
    desc: "Six specialized agents run 24/7: Bidding, Creative, Smart Pacing, Signals, OaaS Optimizer, and SyncBrain Router. All within your guardrails.",
    stat: "0 hrs/wk",
    statLabel: "manual bid management",
    detail: "Agents communicate through Kafka event streams. Every decision logged, explainable, reversible. Full override control retained.",
    sec1Title: "Six Specialized Agents",
    sec1Body: "Each agent has a dedicated responsibility. The Bidding Agent optimizes bids using LTV-weighted ROAS targeting. The Creative Agent scores ad variants. Smart Pacing manages budget delivery. Signals Agent routes conversion data. OaaS Optimizer manages performance-based campaigns. SyncBrain routes AI model requests.",
    sec2Title: "Event-Driven Architecture",
    sec2Body: "Agents communicate asynchronously through Kafka event streams. When the Bidding Agent adjusts a bid, an event is emitted that triggers the Pacing Agent to rebalance the budget. Every decision is logged, explainable, and reversible.",
    sec3Title: "Guardrails & Override Control",
    sec3Body: "Set campaign-level guardrails for max bid, daily budget, stop-loss thresholds, and platform-specific constraints. Every agent action is validated against guardrails before execution. Full manual override available at any time.",
    capabilities: [
      "6 autonomous AI agents operating 24/7",
      "LTV-weighted ROAS bidding optimization",
      "Creative variant scoring and rotation",
      "Smart budget pacing across campaigns",
      "OaaS performance-based optimization",
      "Kafka event-driven agent communication",
    ],
    useCases: [
      { title: "Multi-Platform Advertisers", desc: "Run 5+ campaigns across Meta, Google, TikTok with autonomous bid adjustments that respond to real-time performance." },
      { title: "Performance Agencies", desc: "Manage dozens of client campaigns with agent guardrails per client. All actions logged for audit compliance." },
      { title: "E-commerce Brands", desc: "Let the Creative Agent automatically rotate ad variants based on ROAS while Bidding Agent finds the optimal CPA." },
    ],
  },

  // ── 4. SyncBrain ──────────────────────────────────────────
  {
    id: "syncbrain",
    label: "SyncBrain\u2122",
    icon: "\u2B21",
    color: K.green,
    tagline: "Seven models. One routing brain.",
    desc: "SyncBrain selects the optimal AI model for every task based on type, budget, confidence, and latency. Cost-aware, quality-first.",
    stat: "12ms",
    statLabel: "routing decision",
    detail: "When monthly AI spend exceeds 80%, SyncBrain auto-routes to cheapest models. Confidence scores and model comparison in the canvas.",
    sec1Title: "Intelligent Model Routing",
    sec1Body: "SyncBrain evaluates every incoming AI request against five dimensions: task type (analysis, creative, classification), required confidence, latency budget, cost sensitivity, and current model availability. It then selects the optimal model in under 12ms.",
    sec2Title: "Multi-Model Support",
    sec2Body: "SyncBrain routes across GPT-4o (complex reasoning), GPT-4o-mini (classification, routing), Claude (analysis), Gemini Flash (speed-critical tasks), LLaMA (cost-sensitive batch processing), and custom fine-tuned models. Each model has a cost and quality profile.",
    sec3Title: "Auto Cost Optimization",
    sec3Body: "When monthly AI spend exceeds 80% of the budget, SyncBrain automatically routes to cheaper models while maintaining minimum confidence thresholds. Model performance is continuously tracked and compared in the analytics canvas.",
    capabilities: [
      "Multi-model AI routing (GPT-4o, Claude, Gemini, LLaMA)",
      "12ms routing decisions at P99",
      "Cost-aware model selection with budget caps",
      "Automatic cost optimization at 80% spend threshold",
      "Model performance comparison dashboard",
      "Custom model profiles and routing rules",
    ],
    useCases: [
      { title: "High-Volume Advertisers", desc: "Route millions of bid decisions through LLaMA for cost efficiency while sending complex creative analysis to GPT-4o." },
      { title: "Data-Driven Teams", desc: "Use SyncBrain's model comparison dashboard to measure which AI model drives the best ROAS for each task type." },
      { title: "Cost-Conscious Operations", desc: "Set monthly AI budget caps and let SyncBrain auto-optimize model selection to stay within limits." },
    ],
  },

  // ── 5. Autonomous Bidding ─────────────────────────────────
  {
    id: "autonomous-bidding",
    label: "Autonomous Bidding",
    icon: "\u26A0",
    color: K.blue,
    tagline: "LTV-informed bids. Real-time adjustments.",
    desc: "AI-driven bidding engine that evaluates LTV/CAC ratios, day-parting patterns, and stop-loss conditions. Adjusts bids across all platforms autonomously.",
    stat: "847",
    statLabel: "decisions per day",
    detail: "Groq Llama 3.1 fast-path batch scoring with sub-200ms latency. Heuristic fallback when AI unavailable. Configurable 5-15 minute cycles.",
    sec1Title: "LTV-Weighted Bid Optimization",
    sec1Body: "Bids are driven by predicted LTV, not raw conversion value. ROAS > 4.0 targets get bid increases of 5-15%. Underperformers below 1.0 ROAS see aggressive 25-40% decreases. All decisions logged and reversible.",
    sec2Title: "Stop-Loss Circuit Breakers",
    sec2Body: "Four automatic triggers: spend exceeding time ratio by 50%+, CPA > 2.5x target, ROAS < 0.5x target, LTV/CAC < 1.0. Stop-loss can freeze virtual cards, pause campaigns, or send Slack approval requests for human review.",
    sec3Title: "Cross-Platform Budget Arbitrage",
    sec3Body: "When ROAS differential between platforms exceeds 2x, the engine automatically shifts budget from worst to best performers. Max 20% shift from worst, max 30% increase for best. Configurable thresholds and manual override.",
    capabilities: [
      "LTV/CAC ratio bid evaluation",
      "Day-parting weight matrix (168 values)",
      "Stop-loss circuit breaker with 4 triggers",
      "Cross-platform budget arbitrage",
      "Groq fast-path scoring (<200ms)",
      "Slack approval workflow for large changes",
    ],
    useCases: [
      { title: "Multi-Platform Scale", desc: "Run hundreds of campaigns across 5+ platforms with per-campaign bid strategies that adjust in real-time to market conditions." },
      { title: "Risk-Averse Brands", desc: "Set conservative stop-loss thresholds and require Slack approval for any bid change above 20%. Full control with AI efficiency." },
      { title: "Agency Operations", desc: "Client-specific guardrails ensure no campaign overspends. All bid changes logged for client reporting and audit compliance." },
    ],
  },

  // ── 6. Fraud & IVT ────────────────────────────────────────
  {
    id: "fraud-ivt",
    label: "Fraud & IVT",
    icon: "\u2B17",
    color: K.danger,
    tagline: "Bot traffic poisons your model. We stop it.",
    desc: "Real-time IVT detection: IP reputation, browser fingerprinting, behavioral velocity, and KIKI's proprietary bot graph.",
    stat: "99.2%",
    statLabel: "IVT detection rate",
    detail: "0.03% false positive rate. Quarantine mode for edge cases. All blocked events logged with reason code and fraud score.",
    sec1Title: "Multi-Layer Detection",
    sec1Body: "Every incoming signal is scored against five detection layers: IP reputation databases, browser fingerprinting, behavioral velocity analysis, device fingerprint correlation, and KIKI's proprietary bot graph network.",
    sec2Title: "Model Protection",
    sec2Body: "Fraudulent traffic doesn't just waste spend \u2014 it contaminates your LTV training data. By blocking IVT before enrichment, KIKI ensures your ML models learn from clean, high-quality conversion data.",
    sec3Title: "Quarantine & Review",
    sec3Body: "Edge cases are placed in quarantine mode with configurable confidence thresholds. All blocked events are logged with a reason code, fraud score, and evidence. Review the quarantine queue and release events with one click.",
    capabilities: [
      "5-layer fraud detection pipeline",
      "IP reputation + browser fingerprinting",
      "Behavioral velocity analysis",
      "Proprietary bot graph network",
      "99.2% detection with 0.03% false positives",
      "Quarantine mode for configurable review",
    ],
    useCases: [
      { title: "High-Spend Advertisers", desc: "Protect 6-7 figure monthly ad budgets from bot traffic that inflates conversion metrics and misleads optimization." },
      { title: "LTV Model Training", desc: "Ensure ML training data is clean from IVT contamination so LTV predictions are based on real customer behavior." },
      { title: "Compliance-Critical Audits", desc: "Every blocked event has a detailed audit trail with fraud score, detection layer, and reason code for SOC2 and internal compliance." },
    ],
  },

  // ── 7. Competitive Intelligence ───────────────────────────
  {
    id: "competitive-intel",
    label: "Competitive Intel",
    icon: "\u25C7",
    color: K.gold,
    tagline: "Know what your competitors are doing. In real-time.",
    desc: "Track competitor ad creatives, CPM benchmarks, pricing changes, and positioning gaps across Meta, Google, TikTok, and more.",
    stat: "4",
    statLabel: "platforms monitored",
    detail: "Competitor creative detection, price drop alerts, CPM benchmarking by industry. Automated competitive intelligence gathering.",
    sec1Title: "Creative Monitoring",
    sec1Body: "Automatically detect competitor ad creatives across Meta, Google, and TikTok. Analyze creative themes, ad frequency, messaging angles, and CTAs. See what's working for your competitors in real-time.",
    sec2Title: "Price Drop Detection",
    sec2Body: "Detect competitor price drops with product category, old vs new price, change percentage, and affected platforms. Price drops trigger aggressive arbitrage cycles so you can respond immediately.",
    sec3Title: "CPM Benchmarking",
    sec3Body: "Track CPM benchmarks by platform and industry. Compare your costs against market averages. Monitor changes in competitive landscape and adjust bidding strategy accordingly.",
    capabilities: [
      "Competitor creative detection and analysis",
      "Price drop alerts with change metrics",
      "CPM benchmarking by platform and industry",
      "Competitive positioning gap analysis",
      "Cross-platform competitor tracking",
      "Automated intelligence gathering",
    ],
    useCases: [
      { title: "Competitive Brands", desc: "Monitor competitor ad strategies across platforms and adjust your creative and bidding approach in response to market moves." },
      { title: "Market Intelligence Teams", desc: "Get automated competitive reports with creative analysis, pricing changes, and CPM trends without manual research." },
      { title: "Agency Strategists", desc: "Win more pitches with competitive intelligence data showing deep understanding of client verticals and competitor positioning." },
    ],
  },

  // ── 8. Analytics & Attribution ────────────────────────────
  {
    id: "analytics",
    label: "Analytics & Attribution",
    icon: "\u25C8",
    color: K.oaas,
    tagline: "Cross-platform attribution. One view.",
    desc: "Unified attribution across 14 platforms. Data-driven, last-click, linear, time-decay, position-based \u2014 all powered by your LTV signals.",
    stat: "5",
    statLabel: "attribution models",
    detail: "MMM included for offline spend. Scenario planner models budget reallocation impact before committing.",
    sec1Title: "Multi-Touch Attribution",
    sec1Body: "Five attribution models \u2014 data-driven, last-click, linear, time-decay, and position-based \u2014 run in parallel on every conversion. Compare results side-by-side to understand the true customer journey across all 14 platforms.",
    sec2Title: "LTV-Weighted Reporting",
    sec2Body: "All reports are weighted by predicted LTV, not raw conversion value. This means channels that acquire high-LTV customers get proper credit, while low-quality conversion channels are correctly deprioritized.",
    sec3Title: "Unified Cross-Platform Dashboard",
    sec3Body: "See ROAS, CPA, spend, and conversions across all 14 platforms in a single view. Filter by campaign, platform, date range, and attribution model. Export data for custom analysis or BI tools.",
    capabilities: [
      "5 parallel attribution models",
      "Data-driven, last-click, linear, time-decay, position-based",
      "LTV-weighted attribution reporting",
      "Marketing Mix Modelling with offline spend",
      "Cross-platform unified dashboard",
      "Custom report builder and scheduling",
    ],
    useCases: [
      { title: "Multi-Channel Marketers", desc: "See the true customer journey across Meta, Google, TikTok, LinkedIn, and more with unified attribution." },
      { title: "Analytics Teams", desc: "Compare 5 attribution models side-by-side and export data for custom analysis or BI tools." },
      { title: "CFO & Finance", desc: "LTV-weighted reporting gives accurate channel ROI. Know which platforms actually drive profitable customers, not just conversions." },
    ],
  },

  // ── 9. Marketing Mix Modelling (MMM) ──────────────────────
  {
    id: "mmm",
    label: "Marketing Mix Modelling",
    icon: "\u25A8",
    color: K.oaas,
    tagline: "Offline + online. One ROI model.",
    desc: "Combine online attribution with offline spend data (TV, radio, OOH, print) for a complete marketing ROI picture. Bayesian MMM with saturation curves.",
    stat: "Full",
    statLabel: "channel visibility",
    detail: "Channel saturation curves, marginal ROI per channel, offline-to-online attribution bridging. Bayesian statistical models.",
    sec1Title: "Unified Online + Offline Model",
    sec1Body: "MMM combines your online ad platform data with offline spend (TV, radio, OOH, print, direct mail) into a single Bayesian regression model. Understand the marginal ROI of every channel and optimize the full marketing mix.",
    sec2Title: "Saturation & Diminishing Returns",
    sec2Body: "Model channel saturation curves to identify diminishing returns. Know exactly when you've hit the optimal spend level on each channel before incremental dollars stop producing results.",
    sec3Title: "What-If Budget Simulation",
    sec3Body: "Simulate budget reallocation scenarios before committing dollars. Move 20% from TV to Meta and see the predicted impact on total revenue, CPA, and ROAS across all channels.",
    capabilities: [
      "Bayesian MMM with offline spend integration",
      "Channel saturation and diminishing return curves",
      "Marginal ROI per channel analysis",
      "Offline-to-online attribution bridging",
      "What-if budget simulation",
      "Cross-media reach and frequency modeling",
    ],
    useCases: [
      { title: "Enterprise CMOs", desc: "Defend total marketing budget with a unified ROI model that proves the contribution of every channel, including offline." },
      { title: "Media Planners", desc: "Use saturation curves to find the optimal spend level for each channel and reallocate budget for maximum marginal return." },
      { title: "Holding Companies", desc: "Run MMM at the portfolio level to optimize cross-client media buying power and negotiate better rates." },
    ],
  },

  // ── 10. Scenario Planner ──────────────────────────────────
  {
    id: "scenario-planner",
    label: "Scenario Planner",
    icon: "\u25B6",
    color: K.teal,
    tagline: "Move budget with confidence. See impact before you commit.",
    desc: "Model the impact of budget reallocation, campaign pauses, and platform changes before committing a dollar. Data-driven what-if analysis.",
    stat: "Real-time",
    statLabel: "simulation results",
    detail: "Saturation curves, projected ROAS impact, channel shift simulations, campaign pause impact analysis.",
    sec1Title: "Budget Reallocation Simulation",
    sec1Body: "Model what happens when you shift budget between platforms, campaigns, or channels. See projected ROAS, CPA, and total conversion impact across all attribution models before making changes.",
    sec2Title: "Campaign Pause Impact Analysis",
    sec2Body: "Before pausing an underperforming campaign, see the projected impact on total portfolio performance. The scenario planner accounts for cross-campaign interaction effects and attribution shifts.",
    sec3Title: "Multi-Variant Comparison",
    sec3Body: "Create multiple scenarios side-by-side and compare projected outcomes. Share scenarios with stakeholders and export simulation data for board presentations or client proposals.",
    capabilities: [
      "Budget reallocation simulation",
      "Campaign pause impact analysis",
      "Cross-platform budget shift modeling",
      "Multi-variant scenario comparison",
      "Projected ROAS, CPA, and conversion impact",
      "Scenario export and sharing",
    ],
    useCases: [
      { title: "Media Directors", desc: "Model the impact of shifting 30% of budget from Meta to TikTok before committing. Present data-backed reallocation recommendations to stakeholders." },
      { title: "Performance Managers", desc: "Simulate pausing a low-ROAS campaign and reallocating budget to top performers. See exact projected impact on portfolio KPIs." },
      { title: "Client Strategists", desc: "Build scenario comparisons for client quarterly planning meetings. Let data drive budget recommendations, not intuition." },
    ],
  },

  // ── 11. B2B Attribution ───────────────────────────────────
  {
    id: "b2b-attribution",
    label: "B2B Attribution",
    icon: "\u25A3",
    color: K.blue,
    tagline: "Account-level attribution for B2B marketers.",
    desc: "Attribute revenue to the right accounts and buying committee members. Multi-touch B2B attribution with LinkedIn and Google integration.",
    stat: "Account",
    statLabel: "level attribution",
    detail: "Buying committee mapping, multi-touch touchpoint timelines, LinkedIn and Google B2B attribution, LTV revenue waterfall.",
    sec1Title: "Buying Committee Mapping",
    sec1Body: "Map every touchpoint to the right account and buying committee member. Track how different stakeholders influence the purchase decision across LinkedIn, Google, and other B2B channels.",
    sec2Title: "Multi-Touch B2B Attribution",
    sec2Body: "Attribute revenue across the entire B2B buying journey. Account-level attribution models account for multiple stakeholders, longer sales cycles, and offline conversion paths.",
    sec3Title: "LTV Revenue Waterfall",
    sec3Body: "Track predicted LTV from first touchpoint to closed won. Understand which campaigns, channels, and content drive high-LTV accounts vs low-value leads.",
    capabilities: [
      "Account-level attribution modeling",
      "Buying committee touchpoint mapping",
      "LinkedIn and Google B2B attribution",
      "Multi-stakeholder journey tracking",
      "LTV revenue waterfall reporting",
      "Offline conversion path integration",
    ],
    useCases: [
      { title: "B2B SaaS Companies", desc: "Attribute demo requests and trial signups to the right LinkedIn ad campaigns and Google search terms that drove them." },
      { title: "Enterprise Sales Teams", desc: "See which marketing touchpoints influenced each deal in the pipeline. Arm sales with account-level engagement data." },
      { title: "B2B Marketing Leaders", desc: "Prove marketing sourced revenue with account-level attribution. Defend budget with LTV-weighted pipeline reporting." },
    ],
  },

  // ── 12. Creative Library & AI Generation ───────────────────
  {
    id: "creative-library",
    label: "Creative Library",
    icon: "\u2728",
    color: K.oaas,
    tagline: "Generate, test, optimize ad creatives with AI.",
    desc: "Manage ad creative assets, generate new variants with AI GPT-4o + DALL-E pipeline, detect fatigue, and auto-rotate underperformers.",
    stat: "AI",
    statLabel: "creative generation",
    detail: "Creative fatigue detection triggers automatic replacement. Variant scoring based on ROAS and CTR. A/B test framework built-in.",
    sec1Title: "Creative Asset Management",
    sec1Body: "Upload, organize, and manage all ad creative assets in one library. Tag by campaign, platform, audience, and creative theme. Version history for every asset.",
    sec2Title: "AI Creative Generation",
    sec2Body: "Generate new ad creatives using GPT-4o + DALL-E pipeline. Input a campaign brief and audience context, and the AI produces headlines, body text, CTAs, and image concepts ready for A/B testing.",
    sec3Title: "Fatigue Detection & Rotation",
    sec3Body: "Automatically detect when creatives are experiencing fatigue based on consecutive low ROAS days. Trigger automatic creative replacement or rotation to fresh variants without manual intervention.",
    capabilities: [
      "Creative asset management and organization",
      "AI-powered creative generation (GPT-4o + DALL-E)",
      "Creative fatigue detection",
      "Automatic creative rotation",
      "Variant ROAS and CTR scoring",
      "A/B test framework and reporting",
    ],
    useCases: [
      { title: "Creative Teams", desc: "Generate 10+ creative variants from a single brief in minutes. Test, score, and scale winners automatically." },
      { title: "Performance Marketers", desc: "Never run fatigued creatives again. Automatic detection and rotation keeps campaigns fresh and ROAS high." },
      { title: "Agency Creative Ops", desc: "Manage hundreds of creative assets across dozens of clients. AI generation scales output without scaling headcount." },
    ],
  },

  // ── 13. CRM with LTV Pipeline ─────────────────────────────
  {
    id: "crm-ltv",
    label: "CRM with LTV Pipeline",
    icon: "\u25C6",
    color: K.blue,
    tagline: "Your CRM, powered by LTV predictions.",
    desc: "Track contacts through funnel with full ad attribution. LTV predictions, lead scores, buying committee visibility, AI next-action recommendations.",
    stat: "LTV",
    statLabel: "powered pipeline",
    detail: "Ad touchpoint timeline per contact. LTV-weighted lead scoring. AI-suggested next actions. Full funnel visibility from first click to closed won.",
    sec1Title: "Ad-Touchpoint Timeline",
    sec1Body: "Every contact has a complete timeline of ad touchpoints across all platforms. See which campaigns, creatives, and channels influenced each lead from first impression to conversion.",
    sec2Title: "LTV-Weighted Lead Scoring",
    sec2Body: "Leads are scored by predicted LTV, not just engagement. A lead from a high-LTV segment scores higher than one from a low-LTV segment, even with identical engagement metrics.",
    sec3Title: "AI Next-Action Recommendations",
    sec3Body: "The system analyzes each contact's journey and recommends the next best action: send a follow-up email, retarget on a specific platform, exclude from low-value campaigns, or route to sales.",
    capabilities: [
      "Complete ad touchpoint timeline per contact",
      "LTV-weighted lead scoring",
      "Buying committee mapping",
      "AI next-action recommendations",
      "Full funnel visibility (first click to won)",
      "Platform-agnostic contact tracking",
    ],
    useCases: [
      { title: "B2B Sales Teams", desc: "See every ad touchpoint that influenced a deal. Arm sales with data on which campaigns and content drove each opportunity." },
      { title: "Demand Gen Marketers", desc: "Score leads by predicted LTV, not just form fills. Focus sales effort on high-LTV segments identified by ML models." },
      { title: "Revenue Operations", desc: "Unify ad platform data with CRM pipeline. Full attribution from first click to closed won revenue." },
    ],
  },

  // ── 14. Influencer Attribution ─────────────────────────────
  {
    id: "influencer",
    label: "Influencer Attribution",
    icon: "\u2606",
    color: K.gold,
    tagline: "Measure influencer ROI like any other channel.",
    desc: "Track influencer conversions via promo codes, attribute dark social traffic, measure creator LTV uplift, and model untracked word-of-mouth revenue.",
    stat: "Full",
    statLabel: "influencer ROI",
    detail: "Promo code tracking, dark social attribution, creator LTV uplift analysis, word-of-mouth revenue modeling.",
    sec1Title: "Influencer Conversion Tracking",
    sec1Body: "Track every influencer-driven conversion via unique promo codes, referral links, and UTMs. Attribute revenue to specific creators and campaigns with the same accuracy as any ad platform.",
    sec2Title: "Dark Social Attribution",
    sec2Body: "Model untracked word-of-mouth traffic from influencer content shared via messaging apps, email, and other dark social channels. Use statistical models to attribute conversions that would otherwise appear as direct traffic.",
    sec3Title: "Creator LTV Analysis",
    sec3Body: "Measure the long-term value of customers acquired through each creator. Compare influencer-acquired customer LTV against paid channel LTV to understand true creator ROI beyond first-touch metrics.",
    capabilities: [
      "Promo code and referral link tracking",
      "Dark social traffic attribution",
      "Creator-level LTV uplift analysis",
      "Word-of-mouth revenue modeling",
      "Cross-platform influencer campaign management",
      "Influencer vs paid channel LTV comparison",
    ],
    useCases: [
      { title: "DTC Brands", desc: "Measure true ROI of each influencer partnership. Track promo code conversions and attribute revenue to specific creators and campaigns." },
      { title: "Influencer Agencies", desc: "Prove the value of influencer marketing with LTV data. Show clients that influencer-acquired customers outperform paid channels." },
      { title: "Performance Marketers", desc: "Include influencer channels in your full attribution model. Compare influencer LTV against Meta, Google, and TikTok for true channel mix optimization." },
    ],
  },

  // ── 15. Virtual Cards ─────────────────────────────────────
  {
    id: "virtual-cards",
    label: "Virtual Cards & Wallet",
    icon: "\uD83D\uDCB3",
    color: K.gold,
    tagline: "Campaign-level spend control.",
    desc: "Issue virtual cards per campaign, vendor, or platform. Set limits, merchant restrictions, velocity controls, and auto stop-loss. All tracked to the campaign.",
    stat: "Unlimited",
    statLabel: "virtual cards",
    detail: "Powered by Stripe Issuing. PCI DSS compliant. USD, EUR, GBP. Real-time authorization logging.",
    sec1Title: "Campaign-Level Spend Control",
    sec1Body: "Every campaign gets its own virtual card with configurable spend limits, merchant category restrictions, and velocity controls. No more shared corporate cards or manual expense reconciliation.",
    sec2Title: "Real-Time Authorization",
    sec2Body: "Every card authorization is evaluated in real-time against campaign budgets, stop-loss thresholds, and merchant restrictions. Authorizations are logged immediately with full context including campaign ID, vendor, and amount.",
    sec3Title: "Multi-Currency & Compliance",
    sec3Body: "Issue cards in USD, EUR, and GBP with automatic currency conversion. PCI DSS compliant. All transactions are tracked at the campaign level with full audit trail for SOC2 and financial compliance.",
    capabilities: [
      "Unlimited virtual cards per campaign/vendor",
      "Configurable spend limits and merchant restrictions",
      "Velocity controls and auto stop-loss",
      "Real-time authorization logging",
      "Multi-currency support (USD, EUR, GBP)",
      "PCI DSS compliant with full audit trail",
    ],
    useCases: [
      { title: "Performance Agencies", desc: "Issue cards per client campaign with hard spend limits. All transactions automatically attributed to the correct client for billing." },
      { title: "Enterprise Marketing Teams", desc: "Give each campaign manager a card with per-platform limits. Auto stop-loss prevents budget overrun on underperforming channels." },
      { title: "Finance Operations", desc: "Replace manual expense reports with campaign-level card data. Real-time authorization feeds into accounting and billing systems." },
    ],
  },

  // ── 16. OaaS — Optimization as a Service ──────────────────
  {
    id: "oaas",
    label: "OaaS Optimization",
    icon: "\u2B22",
    color: K.mint,
    tagline: "We manage your campaigns. You keep the upside.",
    desc: "Fully managed optimization service. 1.35% management fee of ad spend + 5% performance bonus on ROAS uplift. Dedicated CSM, contractual ROAS targets.",
    stat: "1.35%",
    statLabel: "management fee",
    detail: "Performance-based pricing. Monthly P&L reporting. Quarterly business reviews. White-glove onboarding. Contractual ROAS uplift targets.",
    sec1Title: "Fully Managed Service",
    sec1Body: "KIKI's team of optimization experts runs your campaigns 24/7 using the full platform: all 6 AI agents, SyncBrain routing, fraud protection, and LTV enrichment. You get a dedicated Customer Success Manager and monthly P&L reports.",
    sec2Title: "Performance-Based Pricing",
    sec2Body: "You pay 1.35% of managed ad spend plus 5% of verified ROAS uplift above baseline. If we don't improve your ROAS, you don't pay the performance bonus. Contractual ROAS targets agreed upfront.",
    sec3Title: "Quarterly Business Reviews",
    sec3Body: "Every quarter, your CSM presents a full platform performance review: ROAS trends, LTV analysis, competitive positioning, creative performance, and strategic recommendations for the next quarter.",
    capabilities: [
      "Fully managed campaign optimization",
      "All 6 AI agents running your campaigns",
      "Dedicated CSM with quarterly reviews",
      "Contractual ROAS uplift targets",
      "1.35% management fee + 5% bonus",
      "White-glove onboarding and migration",
    ],
    useCases: [
      { title: "Growing DTC Brands", desc: "Your team knows the product but not the ad platforms. Let KIKI's experts run your campaigns while you focus on product and operations." },
      { title: "Agencies Scaling Up", desc: "White-label OaaS as your own managed service. KIKI handles the optimization, you handle the client relationship." },
      { title: "Enterprise Marketing Teams", desc: "Supplement your in-house team with KIKI's optimization expertise. Performance-based pricing means you only pay for results." },
    ],
  },

  // ── 17. Profit Margin Analysis ────────────────────────────
  {
    id: "profit-margin",
    label: "Profit Margin Analysis",
    icon: "\u25B7",
    color: K.gold,
    tagline: "Know your true profitability, SKU by SKU.",
    desc: "SKU-level gross margin analysis. Margin-adjusted CAC by campaign and creative. Low-margin product flagging. Contribution margin reporting.",
    stat: "SKU",
    statLabel: "level analysis",
    detail: "Connect e-commerce platform for real-time margin data. Margin-adjusted ROAS and CAC reporting. Low-margin product alerts.",
    sec1Title: "SKU-Level Gross Margin",
    sec1Body: "Import gross margin data from your e-commerce platform (Shopify, etc.) and see true profitability at the SKU level. Know which products are actually profitable after ad costs.",
    sec2Title: "Margin-Adjusted Campaign ROI",
    sec2Body: "Campaign ROAS and CAC are adjusted by product margin. A campaign selling high-margin products looks different than one selling low-margin items. Make optimization decisions based on true contribution margin.",
    sec3Title: "Low-Margin Product Alerts",
    sec3Body: "Get automatically alerted when campaigns are spending aggressively on low-margin or negative-margin products. Pause or adjust campaigns before they destroy profit, not just revenue.",
    capabilities: [
      "SKU-level gross margin analysis",
      "Margin-adjusted campaign ROAS and CAC",
      "Contribution margin per creative variant",
      "Low-margin product flagging and alerts",
      "E-commerce platform integration",
      "Profitability trend reporting",
    ],
    useCases: [
      { title: "E-commerce CFOs", desc: "Stop optimizing for revenue. Know your true profitability at the SKU level and optimize campaigns for contribution margin, not top-line ROAS." },
      { title: "Performance Managers", desc: "Bid more aggressively on high-margin products and throttle spend on low-margin items. Margin-aware optimization protects profitability." },
      { title: "Retail Brands", desc: "Understand the full profit picture across thousands of SKUs. Flag campaigns that drive volume but destroy margin." },
    ],
  },

  // ── 18. Anomaly Detection ─────────────────────────────────
  {
    id: "anomaly-detection",
    label: "Anomaly Detection",
    icon: "\u26A1",
    color: K.warn,
    tagline: "Catch problems before they cost you.",
    desc: "Real-time anomaly detection across ROAS drops, CTR spikes, CAC outliers, budget overpacing, and signal quality degradation. Automated alerts and resolution workflows.",
    stat: "Real-time",
    statLabel: "monitoring",
    detail: "Configurable alert thresholds. Multi-channel notifications (in-app, email, Slack). Automated resolution workflows.",
    sec1Title: "Multi-Metric Anomaly Detection",
    sec1Body: "Monitor ROAS, CTR, CPA, CAC, spend velocity, conversion rate, signal quality, and LTV prediction confidence. Detect anomalies across all metrics simultaneously with configurable sensitivity.",
    sec2Title: "Intelligent Alerting",
    sec2Body: "Alerts are routed through channels based on severity: in-app notifications for warnings, Slack for high-priority alerts, email for critical issues. Configurable escalation paths ensure the right people are notified.",
    sec3Title: "Automated Resolution Workflows",
    sec3Body: "Configure auto-resolution actions: pause underperforming campaigns, reduce bids on anomaly-affected ad sets, re-route traffic to stable campaigns, or notify the AI agents to adjust strategy.",
    capabilities: [
      "Real-time multi-metric anomaly detection",
      "Configurable sensitivity and thresholds",
      "Multi-channel alerting (in-app, Slack, email)",
      "Escalation path configuration",
      "Automated resolution workflows",
      "Anomaly history and trend analysis",
    ],
    useCases: [
      { title: "Always-On Campaigns", desc: "Never miss a ROAS crash or spend spike. Get alerted instantly when something goes wrong and let automated workflows contain the damage." },
      { title: "Lean Marketing Teams", desc: "Monitor dozens of campaigns without a dedicated analytics team. Anomaly detection alerts you only when something needs attention." },
      { title: "Agency Operations", desc: "Client campaigns need 24/7 monitoring. Anomaly detection + automated resolution ensures client SLAs are met without overnight staffing." },
    ],
  },

  // ── 19. Workflow Automation ───────────────────────────────
  {
    id: "workflow-automation",
    label: "Workflow Automation",
    icon: "\u21BA",
    color: K.teal,
    tagline: "Automate every repetitive task.",
    desc: "No-code automation builder. Trigger actions based on campaign events, schedule, or AI decisions. Connect campaigns, alerts, budgets, and reporting into automated workflows.",
    stat: "No-code",
    statLabel: "automation builder",
    detail: "Schedule triggers, Kafka event conditions, Slack alerts, wallet top-ups, campaign pauses, SyncBrain analysis runs.",
    sec1Title: "Visual Workflow Builder",
    sec1Body: "Build automations with a drag-and-drop interface. Triggers: schedule, campaign event (ROAS drop, spend threshold), Kafka event, anomaly detection, API webhook. Actions: pause campaign, send Slack alert, adjust budget, top up wallet, run analysis.",
    sec2Title: "Event-Driven Automation",
    sec2Body: "Automations respond to Kafka events in real-time. When the Bidding Agent makes a decision, workflows can trigger: log to audit, notify Slack, adjust budget, or rebalance portfolio.",
    sec3Title: "Scheduled Operations",
    sec3Body: "Schedule recurring operations: weekly campaign report generation and email, daily budget rebalancing, hourly performance checks, monthly invoice generation and billing sync.",
    capabilities: [
      "Visual no-code workflow builder",
      "Event-driven (Kafka) trigger system",
      "Scheduled and recurring operations",
      "100+ action types",
      "Slack, email, and webhook integrations",
      "Workflow version history and rollback",
    ],
    useCases: [
      { title: "Media Operations", desc: "Automate daily budget rebalancing, weekly report generation, and campaign pause on ROAS drop. Free up hours of manual work every day." },
      { title: "Performance Agencies", desc: "Standardize campaign management processes across clients. Build once, apply to all. Consistent SLAs and reporting." },
      { title: "Enterprise Teams", desc: "Connect KIKI to your existing stack via webhooks. Trigger workflows from Salesforce, HubSpot, or custom systems." },
    ],
  },

  // ── 20. Reports & Dashboards ──────────────────────────────
  {
    id: "reports",
    label: "Reports & Dashboards",
    icon: "\u25A1",
    color: K.blue,
    tagline: "Build any report. Share with anyone.",
    desc: "Custom report builder with drag-and-drop blocks. Schedule automated delivery. White-label exports for clients. PDF, CSV, XLSX formats.",
    stat: "Custom",
    statLabel: "report builder",
    detail: "Drag-and-drop block builder, white-label PDF exports, automated scheduling, client-facing dashboards.",
    sec1Title: "Custom Report Builder",
    sec1Body: "Build reports by dragging and dropping blocks: ROAS charts, CPA trends, attribution comparisons, creative performance tables, anomaly timelines, and more. Every dashboard page is a potential report block.",
    sec2Title: "Automated Scheduling",
    sec2Body: "Schedule reports to generate and deliver automatically: daily performance summaries, weekly campaign deep-dives, monthly P&L statements. Deliver via email, Slack, or webhook.",
    sec3Title: "White-Label Client Reports",
    sec3Body: "Generate client-facing reports with your own branding. White-label PDF exports with custom logo, color scheme, and domain. Perfect for agencies reporting to clients.",
    capabilities: [
      "Drag-and-drop report block builder",
      "Automated scheduling and delivery",
      "White-label PDF exports",
      "CSV, XLSX, PDF format support",
      "Multi-platform data blending",
      "Client-facing dashboard sharing",
    ],
    useCases: [
      { title: "Agency Client Reporting", desc: "Generate white-label client reports automatically every week. Your logo, your branding, KIKI's data." },
      { title: "Internal Performance Reviews", desc: "Build custom dashboards for each team: media buying, creative, analytics, executive. Scheduled delivery every Monday morning." },
      { title: "CFO & Finance Teams", desc: "Monthly P&L reports with full platform spend, margin analysis, and LTV trends. Automated generation and delivery." },
    ],
  },

  // ── 21. Data Warehouse Export ─────────────────────────────
  {
    id: "data-warehouse",
    label: "Data Warehouse Export",
    icon: "\u25A9",
    color: K.oaas,
    tagline: "Export enriched data to your warehouse.",
    desc: "Stream enriched signal data, LTV predictions, and campaign analytics to BigQuery, Snowflake, Redshift, or S3. Configurable sync schedules.",
    stat: "Real-time",
    statLabel: "data sync",
    detail: "Schema browser, incremental export, configurable sync schedules. Full export history and monitoring.",
    sec1Title: "Warehouse Integrations",
    sec1Body: "Export to BigQuery, Snowflake, Redshift, or S3 with native connectors. Full schema browser so you can select exactly which tables and fields to sync.",
    sec2Title: "Incremental Sync",
    sec2Body: "Efficient incremental syncs ensure only new and changed data is transferred. Configurable sync schedules from real-time streaming to daily batch exports.",
    sec3Title: "Data Quality Monitoring",
    sec3Body: "Monitor export success rates, data volume, and sync latency. Alert on failed exports with automatic retry. Full export history for audit and troubleshooting.",
    capabilities: [
      "BigQuery, Snowflake, Redshift, S3 export",
      "Incremental sync (new/changed data only)",
      "Configurable sync schedules",
      "Schema browser and field selector",
      "Export quality monitoring and alerts",
      "Full export history and audit log",
    ],
    useCases: [
      { title: "Data Engineering Teams", desc: "Stream enriched signal data directly into your existing data warehouse. No ETL pipeline needed." },
      { title: "Analytics Teams", desc: "Query KIKI data alongside your other data sources in your BI tool of choice. Full schema visibility." },
      { title: "Enterprise Data Ops", desc: "Configure sync schedules that match your data processing SLAs. Monitor export health alongside your other data pipelines." },
    ],
  },

  // ── 22. Consent & Privacy Management ──────────────────────
  {
    id: "consent-privacy",
    label: "Consent & Privacy",
    icon: "\u2714",
    color: K.teal,
    tagline: "Privacy-compliant advertising. Built-in.",
    desc: "Full consent management integrated into the signal pipeline. GDPR/CCPA validation, cookie consent configuration, UID2/Privacy Sandbox coverage, data subject request handling.",
    stat: "GDPR",
    statLabel: "compliant",
    detail: "Consent validation before every conversion. Data retention policy enforcement. Automated GDPR delete/export requests.",
    sec1Title: "Consent Validation Pipeline",
    sec1Body: "Every conversion is validated against GDPR/CCPA/GPC consent before processing. If consent is not valid, the event is blocked before enrichment. Full consent audit trail maintained for every signal.",
    sec2Title: "Data Subject Request Handling",
    sec2Body: "Automated GDPR data subject request handling. Process delete and export requests for user data across all connected platforms. Full compliance with 30-day SLA.",
    sec3Title: "Privacy Technology Integration",
    sec3Body: "Built-in UID2 and Privacy Sandbox coverage. Monitor consent rates by jurisdiction. SDK-level consent signals (IAB TCF 2.2) processed automatically.",
    capabilities: [
      "Consent validation in CAPI pipeline",
      "GDPR/CCPA/GPC compliance",
      "Automated data subject request handling",
      "UID2 and Privacy Sandbox coverage",
      "IAB TCF 2.2 consent signal processing",
      "Data retention policy automation",
    ],
    useCases: [
      { title: "Privacy-Compliant Brands", desc: "Ensure every conversion processed through KIKI has valid consent. Block non-consented events before they reach ad platforms." },
      { title: "Legal & Compliance Teams", desc: "Automated GDPR request handling with full audit trail. Prove compliance with every signal's consent status." },
      { title: "Publishers & Ad Networks", desc: "Integrate consent signals directly into the CAPI pipeline. Support UID2 and Privacy Sandbox without separate infrastructure." },
    ],
  },

  // ── 23. Security & Compliance ─────────────────────────────
  {
    id: "security-compliance",
    label: "Security & Compliance",
    icon: "\u26BF",
    color: K.blue,
    tagline: "SOC2 Type II. Enterprise-grade security.",
    desc: "TLS 1.3, AES-256, mTLS, zero-trust RBAC, immutable audit logs. SOC2 Type II certified. Quarterly penetration testing.",
    stat: "SOC2",
    statLabel: "Type II certified",
    detail: "Immutable cryptographically hashed audit log for every action. Quarterly penetration testing. Zero-trust architecture.",
    sec1Title: "Enterprise Security Architecture",
    sec1Body: "TLS 1.3 for all data in transit, AES-256 for data at rest, mTLS for service-to-service communication. Zero-trust RBAC with granular permission controls. Every API request authenticated and authorized.",
    sec2Title: "Immutable Audit Log",
    sec2Body: "Every action across the platform is recorded in a cryptographically hashed immutable audit log: agent decisions, billing events, API calls, GDPR requests, admin actions. Tamper-evident chain of custody.",
    sec3Title: "Certifications & Testing",
    sec3Body: "SOC2 Type II certified. Quarterly penetration testing by independent firms. Annual security review. Custom enterprise SLAs available including 99.99% uptime guarantee.",
    capabilities: [
      "SOC2 Type II certification",
      "TLS 1.3, AES-256, mTLS encryption",
      "Zero-trust RBAC permission model",
      "Immutable cryptographic audit log",
      "Quarterly penetration testing",
      "Custom enterprise SLAs (99.99% uptime)",
    ],
    useCases: [
      { title: "Enterprise Procurement", desc: "SOC2 Type II certification and enterprise SLAs meet procurement requirements. Custom data residency available (EU/US/APAC)." },
      { title: "Compliance Officers", desc: "Full audit trail for every platform action. Tamper-evident logging meets SOC2, SOX, and internal compliance requirements." },
      { title: "Security Teams", desc: "Zero-trust architecture with granular RBAC. Quarterly pen testing results available upon request. Custom security review process." },
    ],
  },

  // ── 24. AI Ops & MLOps ───────────────────────────────────
  {
    id: "ai-ops",
    label: "AI Ops & MLOps",
    icon: "\u25CB",
    color: K.mint,
    tagline: "Manage your AI models in production.",
    desc: "Model registry, training queue, A/B experiments, feature importance tracking, drift detection, automatic retraining. Full MLOps lifecycle management.",
    stat: "Full",
    statLabel: "MLOps lifecycle",
    detail: "Per-tenant model versioning. Feature importance tracking. Drift detection. Automatic retraining every 6 hours. Model registry with promotion/demotion.",
    sec1Title: "Model Registry & Versioning",
    sec1Body: "Every model version is tracked in the registry with training data snapshot, feature set, hyperparameters, and performance metrics (R\u00B2, MAPE). Promote or demote model versions with one click.",
    sec2Title: "Automatic Training Pipeline",
    sec2Body: "Models are automatically retrained every 6 hours as new data arrives. Training quality gates ensure only models that meet performance thresholds are promoted to production.",
    sec3Title: "Drift Detection & Alerts",
    sec3Body: "Monitor prediction drift, feature drift, and model performance degradation. Automatic alerts when model accuracy drops below thresholds. Trigger retraining or rollback to previous version.",
    capabilities: [
      "Model registry with versioning",
      "Automatic retraining every 6 hours",
      "A/B model experiments",
      "Feature importance tracking",
      "Drift detection and alerts",
      "Training quality gates and promotion",
    ],
    useCases: [
      { title: "Data Science Teams", desc: "Manage the full model lifecycle from training to production. A/B test model versions and promote winners with confidence." },
      { title: "ML Engineers", desc: "Automatic retraining pipelines reduce operational overhead. Drift detection catches model degradation before it impacts predictions." },
      { title: "Technical Product Managers", desc: "Full visibility into model performance: R\u00B2, MAPE, feature importance, training history. Data-driven decisions about model investments." },
    ],
  },

  // ── 25. Platform Integrations ─────────────────────────────
  {
    id: "platform-integrations",
    label: "Platform Integrations",
    icon: "\u29D6",
    color: K.teal,
    tagline: "14 ad platforms. One integration.",
    desc: "Native OAuth + CAPI integrations with every major ad platform. Connect once, enrich everywhere. Automatic token refresh and health monitoring.",
    stat: "14",
    statLabel: "integrated platforms",
    detail: "Meta, Google, TikTok, LinkedIn, YouTube, Snapchat, Pinterest, Amazon DSP, Reddit, DV360, X Ads, TradeDesk, Criteo, AppNexus.",
    sec1Title: "One-Click Platform Connections",
    sec1Body: "Connect each platform with native OAuth. No API key management, no webhook configuration, no maintenance. KIKI handles authentication, token refresh, and connection health monitoring automatically.",
    sec2Title: "Automatic Token Management",
    sec2Body: "Platform API tokens are automatically refreshed before they expire. Token health is monitored hourly. If a token fails to refresh, you get an alert before any data flow is interrupted.",
    sec3Title: "Unified Campaign Management",
    sec3Body: "Manage campaigns across all platforms from a single interface. Create, pause, adjust budgets, and analyze performance without switching between platform dashboards.",
    capabilities: [
      "14 native platform integrations",
      "One-click OAuth connection",
      "Automatic token refresh and monitoring",
      "Unified campaign management",
      "Cross-platform performance analytics",
      "Webhook receivers for all platforms",
    ],
    useCases: [
      { title: "Multi-Platform Advertisers", desc: "Connect all your ad platforms in minutes. Manage campaigns, analyze performance, and optimize across every channel from one place." },
      { title: "Agencies", desc: "Onboard new client accounts instantly with OAuth. No API key sharing, no manual setup. Full platform access in minutes." },
      { title: "Enterprise Marketing Ops", desc: "Standardize platform connections across the organization. Automatic token management eliminates connection downtime." },
    ],
  },
];
