"use client";
import { useState, useEffect, useCallback } from "react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Card, Badge, ProgressBar, Button, AIThinking } from "@/components/ui";
import { useAuth } from "@/hooks/useAuth";
import { K, fmt } from "@/lib/kdls";
import { generatePDF } from "@/lib/pdf";

interface BillingData {
  subscription: {
    plan: string;
    status: string;
    currentPeriodEnd: string;
  } | null;
  usage: Record<string, { quantity: number; cost: number }>;
  totalManagedSpend: number;
  invoices: { id: string; amount: number; status: string; currency: string; periodStart: string; periodEnd: string }[];
  oaas: { totalFees: number; platformFeeRate: number } | null;
}

export default function BillingPage() {
  const { token } = useAuth();
  const [tab, setTab] = useState<"overview" | "invoices">("overview");
  const [billing, setBilling] = useState<BillingData | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchBilling = useCallback(async () => {
    if (!token) return;
    try {
      const res = await fetch("/api/billing", {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (res.ok) {
        const data = await res.json();
        setBilling(data.data || data);
      }
    } catch {
      // keep existing
    } finally {
      setLoading(false);
    }
  }, [token]);

  useEffect(() => {
    fetchBilling();
  }, [fetchBilling]);

  const plan = billing?.subscription;
  const usage = billing?.usage || {};
  const totalSpend = billing?.totalManagedSpend || 0;
  const oaas = billing?.oaas;
  const invoices = billing?.invoices || [];

  const downloadInvoice = async (invoiceId: string) => {
    const inv = invoices.find(i => i.id === invoiceId);
    if (!inv) return;
    await generatePDF({
      filename: `${invoiceId}.pdf`,
      title: `Invoice ${invoiceId}`,
      content: [
        `Amount: ${fmt.currency(inv.amount)} ${inv.currency.toUpperCase()}`,
        `Status: ${inv.status}`,
        `Period: ${new Date(inv.periodStart).toLocaleDateString()} – ${new Date(inv.periodEnd).toLocaleDateString()}`,
        "",
        "This invoice was generated by the KIKI Agent billing engine based on your actual usage and subscription.",
      ],
    });
  };

  const meters = [
    { name: "API Calls", used: usage.api_calls?.quantity || 0, limit: 500000, unit: "calls" },
    { name: "AI Agent Runs", used: usage.ai_agent_runs?.quantity || 0, limit: 2000, unit: "runs" },
    { name: "Storage", used: usage.storage?.quantity || 0, limit: 50, unit: "GB" },
    { name: "Team Seats", used: usage.team_seats?.quantity || 0, limit: 10, unit: "seats" },
    { name: "Webhooks", used: usage.webhooks?.quantity || 0, limit: 20, unit: "endpoints" },
  ];

  return (
    <DashboardLayout>
      <div className="max-w-[1400px] p-[clamp(14px,3vw,28px)]">
        <div className="flex justify-between items-start mb-5">
          <div>
            <h1 className="font-mono font-bold text-lg text-white tracking-tight mb-1">Billing & Plans</h1>
            <p className="font-mono text-[11px] text-gray-500">Current plan · Usage meters · Invoice history</p>
          </div>
          <div className="flex gap-1 p-[3px] rounded-sm bg-g900 border border-g800">
            {(["overview", "invoices"] as const).map(t => (
              <button key={t} onClick={() => setTab(t)}
                className="font-mono text-[10px] font-semibold tracking-widest px-3.5 py-[5px] rounded-sm cursor-pointer"
                style={{ color: tab === t ? K.t1 : K.t4, background: tab === t ? K.g800 : "transparent", border: "none" }}>
                {t.toUpperCase()}
              </button>
            ))}
          </div>
        </div>

        {loading ? (
          <div className="flex justify-center py-15">
            <AIThinking text="Loading billing data..." />
          </div>
        ) : tab === "overview" ? (
          <>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 mb-4">
              <Card accent={K.gold} glow={K.gold}>
                <p className="font-mono text-[10px] tracking-[0.14em] text-gray-600 mb-2">CURRENT PLAN</p>
                <div className="flex items-center gap-2.5 mb-3">
                  <span className="font-mono text-[22px] font-bold text-kgold">{plan?.plan?.toUpperCase() || "FREE"}</span>
                  <Badge color={plan?.status === "active" ? K.mint : K.warn}>{plan?.status?.toUpperCase() || "NONE"}</Badge>
                </div>
                <p className="font-mono text-[10px] text-gray-500 mt-1">
                  {plan?.currentPeriodEnd ? `Renews ${new Date(plan.currentPeriodEnd).toLocaleDateString()}` : "No active subscription"}
                </p>
              </Card>

              <Card>
                <p className="font-mono text-[10px] tracking-[0.14em] text-gray-600 mb-2">TOTAL MANAGED SPEND</p>
                <p className="font-mono text-[28px] font-bold text-white mb-1">${fmt.compact(totalSpend)}</p>
                <p className="font-mono text-[10px] text-gray-500 mb-3">Across all campaigns</p>
              </Card>

              <Card>
                <p className="font-mono text-[10px] tracking-[0.14em] text-gray-600 mb-2">OaaS FEES</p>
                <p className="font-mono text-[28px] font-bold mb-1 text-kmint">
                  {oaas ? `$${oaas.totalFees.toFixed(2)}` : "N/A"}
                </p>
                <p className="font-mono text-[10px] text-gray-500 mb-3">
                  {oaas ? `${(oaas.platformFeeRate * 100).toFixed(1)}% platform fee` : "Not on OaaS plan"}
                </p>
              </Card>
            </div>

            <Card>
              <div className="px-5 py-3.5 border-b border-g800">
                <h2 className="font-mono font-bold text-[13px] text-white">Usage Meters</h2>
              </div>
              {meters.map((m, i) => {
                const pct = m.limit > 0 ? (m.used / m.limit) * 100 : 0;
                const warn = pct > 80;
                return (
                  <div key={i} className="px-5 py-3" style={{ borderBottom: i < meters.length - 1 ? `1px solid ${K.g900}` : undefined }}>
                    <div className="flex justify-between mb-1.5">
                      <span className="font-mono text-[11px] font-semibold text-white">{m.name}</span>
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-[11px]" style={{ color: warn ? K.warn : K.t2 }}>
                          {m.used >= 1000 ? fmt.compact(m.used) : m.used} / {m.limit >= 1000 ? fmt.compact(m.limit) : m.limit} {m.unit}
                        </span>
                        {warn && <Badge color={K.warn}>HIGH</Badge>}
                      </div>
                    </div>
                    <ProgressBar value={pct} color={warn ? K.warn : K.blue} height={4} glow={warn} />
                  </div>
                );
              })}
            </Card>
          </>
        ) : (
          <Card padding={0}>
            <div className="px-5 py-3.5 border-b border-g800">
              <h2 className="font-mono font-bold text-[13px] text-white">Invoice History</h2>
            </div>
            {invoices.length === 0 ? (
              <div className="p-10 text-center">
                <p className="font-mono text-xs text-gray-600">No invoices yet. Invoices are generated monthly based on your usage.</p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                {invoices.map((inv, i) => (
                  <div key={inv.id} className="grid grid-cols-[1fr_120px_120px_100px_90px] gap-3 px-5 py-3.5 items-center hover:bg-[var(--card-hover)] min-w-[600px]"
                    style={{ borderBottom: i < invoices.length - 1 ? `1px solid ${K.g900}` : undefined }}>
                    <div>
                      <p className="font-mono text-[11px] font-semibold text-white mb-0.5">{inv.id}</p>
                      <p className="font-mono text-[10px] text-gray-600">
                        {new Date(inv.periodStart).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })} – {new Date(inv.periodEnd).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
                      </p>
                    </div>
                    <span className="font-mono text-[11px] font-semibold text-white">{fmt.currency(inv.amount)}</span>
                    <Badge color={inv.status === "paid" ? K.mint : inv.status === "open" ? K.gold : K.danger}>{inv.status.toUpperCase()}</Badge>
                    <span className="font-mono text-[10px] text-gray-600">{inv.currency.toUpperCase()}</span>
                    <Button variant="ghost" size="xs" onClick={() => downloadInvoice(inv.id)}>Download ↓</Button>
                  </div>
                ))}
              </div>
            )}
          </Card>
        )}
      </div>
    </DashboardLayout>
  );
}
