"use client";
import { useState, useEffect } from "react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Card, Badge, Button, ScrollableTable } from "@/components/ui";
import { K } from "@/lib/kdls";
import { useAuth } from "@/hooks/useAuth";
import { useInsights } from "@/hooks/useInsights";
import { downloadSimplePDF } from "@/lib/pdf";

interface ReportData {
  agentActions: { total: number; byType: { actionType: string; count: number; avgDurationMs: number }[] };
  campaigns: { total: number; active: number; totalSpend: number; totalRevenue: number; avgRoas: number };
  usage: { totalCost: number; byType: { type: string; totalQuantity: number; totalCost: number }[] };
  generatedAt: string;
}
interface WarehouseFeature {
  id: number; featureName: string; featureValue: number;
  sampleCount: number; mean: number | null; stddev: number | null; updatedAt: string;
}

export default function ReportsPage() {
  const { token } = useAuth();
  const { data: insights } = useInsights();
  const [tab, setTab] = useState<"scheduled" | "templates">("scheduled");
  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [warehouseFeatures, setWarehouseFeatures] = useState<WarehouseFeature[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!token) return;
    Promise.all([
      fetch("/api/reports", { headers: { Authorization: `Bearer ${token}` } }).then(r => r.ok ? r.json() : null),
      fetch("/api/warehouse", { headers: { Authorization: `Bearer ${token}` } }).then(r => r.ok ? r.json() : null),
    ])
      .then(([reports, warehouse]) => {
        if (reports?.data) setReportData(reports.data);
        if (warehouse?.data) setWarehouseFeatures(warehouse.data.features ?? []);
      })
      .catch((err) => { setError(err?.message || "Failed to load data"); setLoading(false); })
      .finally(() => setLoading(false));
  }, [token]);

  const scheduledReports: { name: string; schedule: string; recipients: string; format: string; lastSent: string; nextSend: string; status: string }[] = [];

  const recentExports = warehouseFeatures.length > 0
    ? warehouseFeatures.slice(0, 5).map((f, i) => ({
        name: f.featureName,
        date: new Date(f.updatedAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }),
        size: `${f.sampleCount} samples`,
        format: "Feature",
        status: "completed",
      }))
    : reportData
      ? [
          { name: "Campaign Performance", date: new Date(reportData.generatedAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }), size: `${reportData.campaigns.total} campaigns`, format: "PDF", status: "completed" },
          { name: "Agent Action Log", date: new Date(reportData.generatedAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }), size: `${reportData.agentActions.total} actions`, format: "CSV", status: "completed" },
          { name: "Usage Summary", date: new Date(reportData.generatedAt).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }), size: `$${reportData.usage.totalCost.toFixed(0)} total`, format: "Excel", status: "completed" },
        ]
      : [];

  const templates = [
    { name: "Executive Dashboard", desc: "High-level KPIs, revenue, and ROAS for leadership", icon: "◈", color: K.gold },
    { name: "Campaign Performance", desc: "Detailed per-campaign metrics with channel breakdown", icon: "⬡", color: K.blue },
    { name: "Financial P&L", desc: "Revenue, costs, margins, and month-over-month trends", icon: "▣", color: K.mint },
    { name: "Agent Activity Log", desc: "All AI agent decisions, actions, and performance", icon: "◎", color: K.teal },
    { name: "Competitive Analysis", desc: "Market share, competitor benchmarks, and share of voice", icon: "◉", color: K.oaas },
    { name: "Compliance Audit", desc: "Consent rates, GDPR activity, and data governance", icon: "🔒", color: K.warn },
  ];

  const buildReport = (title: string, desc: string) => {
    const now = new Date().toLocaleString();
    const body = `${desc}\n\nGenerated: ${now}\nReport Type: ${title}\n\nThis report was generated by the KIKI Agent reporting engine. Data is aggregated from your connected ad platforms, AI agent activity logs, and wallet transactions for the selected reporting period.\n\nFor detailed per-metric breakdowns, export individual reports from the Scheduled Reports tab or use the API at /api/reports.`;
    downloadSimplePDF(`${title.replace(/\s+/g, "-").toLowerCase()}.pdf`, title, body);
  };

  return (
    <DashboardLayout>
      <div className="max-w-[1400px] p-[clamp(14px,3vw,28px)]">
        <div className="flex justify-between items-start mb-5 gap-3 flex-wrap">
          <div>
            <h1 className="font-mono font-bold text-lg text-white tracking-tight mb-1">Reports</h1>
            <p className="font-mono text-[11px] text-gray-500">Scheduled reports · Recent exports · Report builder</p>
          </div>
          <div className="flex gap-2">
            <div className="flex gap-1 p-[3px] rounded-sm" style={{ background: K.g900, border: `1px solid ${K.g800}` }}>
              {(["scheduled", "templates"] as const).map(t => (
                <button key={t} onClick={() => setTab(t)}
                  className="font-mono text-[10px] font-semibold tracking-widest px-3.5 py-[5px] rounded-sm cursor-pointer uppercase"
                  style={{ color: tab === t ? K.t1 : K.t4, background: tab === t ? K.g800 : "transparent", border: "none" }}>
                  {t}
                </button>
              ))}
            </div>
            <Button variant="primary" size="sm" onClick={() => buildReport("Custom Report", "A custom report generated on demand from the KIKI Agent reporting engine.")}>+ New Report</Button>
          </div>
        </div>

        {error && (
          <div className="mb-4 p-3 rounded-sm" style={{ background: `${K.danger}12`, border: `1px solid ${K.danger}40` }}>
            <p className="font-mono text-[11px]" style={{ color: K.danger }}>{error}</p>
          </div>
        )}

        {tab === "scheduled" && (
          <>
            <Card padding={0}>
              <div className="px-5 py-3.5" style={{ borderBottom: `1px solid ${K.g800}` }}>
                <h2 className="font-mono font-bold text-[13px] text-white flex items-center gap-2">Scheduled Reports ({scheduledReports.length})</h2>
              </div>
              {loading ? (
                <div className="px-5 py-8 text-center"><span className="font-mono text-[11px] text-gray-500">Loading reports…</span></div>
              ) : scheduledReports.length === 0 ? (
                <div className="px-5 py-8 text-center"><span className="font-mono text-[11px] text-gray-500">No scheduled reports. Create one to automate your reporting.</span></div>
              ) : (
                <ScrollableTable>
                {scheduledReports.map((r, i) => (
                  <div key={i} className="grid grid-cols-[1fr_160px_140px_80px_100px_80px] gap-3 px-5 py-3.5 items-center hover:bg-[var(--card-hover)] min-w-[600px]"
                    style={{ borderBottom: i < scheduledReports.length - 1 ? `1px solid ${K.g900}` : undefined }}>
                    <div>
                      <p className="font-mono text-[11px] font-semibold text-white mb-0.5">{r.name}</p>
                      <p className="font-mono text-[10px] text-gray-600">{r.schedule}</p>
                    </div>
                    <span className="font-mono text-[10px] text-gray-500">{r.recipients}</span>
                    <Badge color={K.blue}>{r.format}</Badge>
                    <span className="font-mono text-[10px] text-gray-600">Last: {r.lastSent}</span>
                    <span className="font-mono text-[10px] text-gray-500">Next: {r.nextSend}</span>
                    <Badge color={K.mint} dot pulse>ACTIVE</Badge>
                  </div>
                ))}
                </ScrollableTable>
              )}
            </Card>

            <Card>
              <div className="px-5 py-3.5" style={{ borderBottom: `1px solid ${K.g800}` }}>
                <h2 className="font-mono font-bold text-[13px] text-white flex items-center gap-2">Recent Exports</h2>
              </div>
              {loading ? (
                <div className="px-5 py-8 text-center"><span className="font-mono text-[11px] text-gray-500">Loading exports…</span></div>
              ) : recentExports.length === 0 ? (
                <div className="px-5 py-8 text-center"><span className="font-mono text-[11px] text-gray-500">No exports yet. Generate a report to see it here.</span></div>
              ) : (
                recentExports.map((e, i) => (
                  <div key={i} className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 px-5 py-3 hover:bg-[var(--card-hover)]"
                    style={{ borderBottom: i < recentExports.length - 1 ? `1px solid ${K.g900}` : undefined }}>
                    <div className="page-header-actions">
                      <Badge color={e.format === "PDF" ? K.danger : e.format === "Excel" ? K.mint : e.format === "CSV" ? K.blue : K.teal}>{e.format}</Badge>
                      <span className="font-mono text-[11px] font-semibold text-white">{e.name}</span>
                    </div>
                    <div className="flex flex-wrap items-center gap-4">
                      <span className="font-mono text-[10px] text-gray-600">{e.date}</span>
                      <span className="font-mono text-[10px] text-gray-500">{e.size}</span>
                      <Badge color={K.mint}>DONE</Badge>
                      <Button variant="ghost" size="xs" onClick={() => downloadSimplePDF(`${e.name.replace(/\s+/g, "-").toLowerCase()}.pdf`, e.name, e.name + "\n\nGenerated: " + e.date + "\nFormat: " + e.format + "\n\nThis report was generated by the KIKI Agent reporting engine.")}>Download ↓</Button>
                    </div>
                  </div>
                ))
              )}
            </Card>
          </>
        )}

        {tab === "templates" && (
          <div>
            <p className="font-mono text-[11px] text-gray-500 mb-4">Choose a template to build a new report</p>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {templates.map((t, i) => (
                <Card key={i} accent={t.color} hover onClick={() => buildReport(t.name, t.desc)} className="cursor-pointer">
                  <div className="flex items-center gap-2.5 mb-2.5">
                    <span className="text-xl" style={{ color: t.color }}>{t.icon}</span>
                    <h3 className="font-mono font-bold text-xs text-white">{t.name}</h3>
                  </div>
                  <p className="font-sans text-[11px] text-gray-500 leading-relaxed">{t.desc}</p>
                  <div className="mt-3">
                    <Button variant="secondary" size="xs" onClick={(e) => { e.stopPropagation(); buildReport(t.name, t.desc); }}>Use Template →</Button>
                  </div>
                </Card>
              ))}
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
