"use client";
import { useState } from "react";
import { DashboardLayout } from "@/components/layout/DashboardLayout";
import { Card, Badge, Button } from "@/components/ui";
import { K } from "@/lib/kdls";
import { downloadSimplePDF } from "@/lib/pdf";

const SCHEDULED_REPORTS = [
  { name: "Weekly Performance Summary", schedule: "Every Monday 8:00 AM", recipients: "sarah@kiki.io, james@kiki.io", format: "PDF", lastSent: "Jul 7, 2026", nextSend: "Jul 14, 2026", status: "active" },
  { name: "Monthly Financial Report", schedule: "1st of each month", recipients: "finance@kiki.io", format: "Excel + PDF", lastSent: "Jul 1, 2026", nextSend: "Aug 1, 2026", status: "active" },
  { name: "Campaign ROAS Deep Dive", schedule: "Every 2 weeks", recipients: "marketing@kiki.io", format: "PDF", lastSent: "Jun 30, 2026", nextSend: "Jul 14, 2026", status: "active" },
];

const RECENT_EXPORTS = [
  { name: "Q2 Performance Analytics", date: "Jul 10, 2026", size: "4.2 MB", format: "PDF", status: "completed" },
  { name: "June Campaign Summary", date: "Jul 8, 2026", size: "2.8 MB", format: "Excel", status: "completed" },
  { name: "Ad Spend by Channel", date: "Jul 5, 2026", size: "1.1 MB", format: "CSV", status: "completed" },
  { name: "Agent Performance Report", date: "Jul 3, 2026", size: "3.6 MB", format: "PDF", status: "completed" },
  { name: "Fraud Detection Summary", date: "Jul 1, 2026", size: "890 KB", format: "PDF", status: "completed" },
];

const TEMPLATES = [
  { name: "Executive Dashboard", desc: "High-level KPIs, revenue, and ROAS for leadership", icon: "◈", color: K.gold },
  { name: "Campaign Performance", desc: "Detailed per-campaign metrics with channel breakdown", icon: "⬡", color: K.blue },
  { name: "Financial P&L", desc: "Revenue, costs, margins, and month-over-month trends", icon: "▣", color: K.mint },
  { name: "Agent Activity Log", desc: "All AI agent decisions, actions, and performance", icon: "◎", color: K.teal },
  { name: "Competitive Analysis", desc: "Market share, competitor benchmarks, and share of voice", icon: "◉", color: K.oaas },
  { name: "Compliance Audit", desc: "Consent rates, GDPR activity, and data governance", icon: "🔒", color: K.warn },
];

export default function ReportsPage() {
  const [tab, setTab] = useState<"scheduled" | "templates">("scheduled");

  const buildReport = (title: string, desc: string) => {
    const now = new Date().toLocaleString();
    const body = `${desc}\n\nGenerated: ${now}\nReport Type: ${title}\n\nThis report was generated by the KIKI Agent reporting engine. Data is aggregated from your connected ad platforms, AI agent activity logs, and wallet transactions for the selected reporting period.\n\nFor detailed per-metric breakdowns, export individual reports from the Scheduled Reports tab or use the API at /api/reports.`;
    downloadSimplePDF(`${title.replace(/\s+/g, "-").toLowerCase()}.pdf`, title, body);
  };

  return (
    <DashboardLayout>
      <div style={{ padding: "24px 28px", maxWidth: 1400 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 22 }}>
          <div>
            <h1 style={{ fontFamily: K.mono, fontWeight: 700, fontSize: 18, color: K.t1, letterSpacing: "-0.02em", marginBottom: 4 }}>Reports</h1>
            <p style={{ fontFamily: K.mono, fontSize: 11, color: K.t3 }}>Scheduled reports · Recent exports · Report builder</p>
          </div>
          <div style={{ display: "flex", gap: 8 }}>
            <div style={{ display: "flex", gap: 4, background: K.g900, border: `1px solid ${K.g800}`, borderRadius: 2, padding: 3 }}>
              {(["scheduled", "templates"] as const).map(t => (
                <button key={t} onClick={() => setTab(t)}
                  style={{ padding: "5px 14px", fontFamily: K.mono, fontSize: 10, fontWeight: 600, letterSpacing: "0.08em", color: tab === t ? K.t1 : K.t4, background: tab === t ? K.g800 : "transparent", border: "none", borderRadius: 2, cursor: "pointer", textTransform: "uppercase" }}>
                  {t}
                </button>
              ))}
            </div>
            <Button variant="primary" size="sm" onClick={() => buildReport("Custom Report", "A custom report generated on demand from the KIKI Agent reporting engine.")}>+ New Report</Button>
          </div>
        </div>

        {tab === "scheduled" && (
          <>
            <Card padding={0}>
              <div style={{ padding: "14px 20px", borderBottom: `1px solid ${K.g800}` }}>
                <h2 style={{ fontFamily: K.mono, fontWeight: 700, fontSize: 13, color: K.t1, display: "flex", alignItems: "center", gap: 8 }}>Scheduled Reports ({SCHEDULED_REPORTS.length}) <Badge color={K.t4} style={{ fontSize: 8 }}>SAMPLE</Badge></h2>
              </div>
              {SCHEDULED_REPORTS.map((r, i) => (
                <div key={i} style={{ padding: "14px 20px", borderBottom: i < SCHEDULED_REPORTS.length - 1 ? `1px solid ${K.g900}` : undefined, display: "grid", gridTemplateColumns: "1fr 160px 140px 80px 100px 80px", gap: 12, alignItems: "center" }}
                  onMouseEnter={e => (e.currentTarget.style.background = K.g850)} onMouseLeave={e => (e.currentTarget.style.background = "transparent")}>
                  <div>
                    <p style={{ fontFamily: K.mono, fontSize: 11, fontWeight: 600, color: K.t1, marginBottom: 2 }}>{r.name}</p>
                    <p style={{ fontFamily: K.mono, fontSize: 9, color: K.t4 }}>{r.schedule}</p>
                  </div>
                  <span style={{ fontFamily: K.mono, fontSize: 9, color: K.t3 }}>{r.recipients}</span>
                  <Badge color={K.blue}>{r.format}</Badge>
                  <span style={{ fontFamily: K.mono, fontSize: 9, color: K.t4 }}>Last: {r.lastSent}</span>
                  <span style={{ fontFamily: K.mono, fontSize: 9, color: K.t3 }}>Next: {r.nextSend}</span>
                  <Badge color={K.mint} dot pulse>ACTIVE</Badge>
                </div>
              ))}
            </Card>

            <Card>
              <div style={{ padding: "14px 20px", borderBottom: `1px solid ${K.g800}` }}>
                <h2 style={{ fontFamily: K.mono, fontWeight: 700, fontSize: 13, color: K.t1, display: "flex", alignItems: "center", gap: 8 }}>Recent Exports <Badge color={K.t4} style={{ fontSize: 8 }}>SAMPLE</Badge></h2>
              </div>
              {RECENT_EXPORTS.map((e, i) => (
                <div key={i} style={{ padding: "10px 20px", borderBottom: i < RECENT_EXPORTS.length - 1 ? `1px solid ${K.g900}` : undefined, display: "flex", alignItems: "center", justifyContent: "space-between" }}
                  onMouseEnter={e2 => (e2.currentTarget.style.background = K.g850)} onMouseLeave={e2 => (e2.currentTarget.style.background = "transparent")}>
                  <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                    <Badge color={e.format === "PDF" ? K.danger : e.format === "Excel" ? K.mint : K.blue}>{e.format}</Badge>
                    <span style={{ fontFamily: K.mono, fontSize: 11, fontWeight: 600, color: K.t1 }}>{e.name}</span>
                  </div>
                  <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
                    <span style={{ fontFamily: K.mono, fontSize: 9, color: K.t4 }}>{e.date}</span>
                    <span style={{ fontFamily: K.mono, fontSize: 9, color: K.t3 }}>{e.size}</span>
                    <Badge color={K.mint}>DONE</Badge>
                    <Button variant="ghost" size="xs" onClick={() => downloadSimplePDF(`${e.name.replace(/\s+/g, "-").toLowerCase()}.pdf`, e.name, e.name + "\n\nGenerated: " + e.date + "\nFormat: " + e.format + "\n\nThis report was generated by the KIKI Agent reporting engine. Data is based on the reporting period ending " + e.date + ".")}>Download ↓</Button>
                  </div>
                </div>
              ))}
            </Card>
          </>
        )}

        {tab === "templates" && (
          <div>
            <p style={{ fontFamily: K.mono, fontSize: 11, color: K.t3, marginBottom: 16 }}>Choose a template to build a new report</p>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12 }}>
              {TEMPLATES.map((t, i) => (
                <Card key={i} accent={t.color} hover onClick={() => buildReport(t.name, t.desc)} style={{ cursor: "pointer" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 10 }}>
                    <span style={{ fontSize: 20, color: t.color }}>{t.icon}</span>
                    <h3 style={{ fontFamily: K.mono, fontWeight: 700, fontSize: 12, color: K.t1 }}>{t.name}</h3>
                  </div>
                  <p style={{ fontFamily: K.sans, fontSize: 11, color: K.t3, lineHeight: 1.5 }}>{t.desc}</p>
                  <div style={{ marginTop: 12 }}>
                    <Button variant="secondary" size="xs" onClick={(e) => { e.stopPropagation(); buildReport(t.name, t.desc); }}>Use Template →</Button>
                  </div>
                </Card>
              ))}
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
