"use client";
import { MarketingLayout } from "@/components/layout/MarketingLayout";
import { K } from "@/lib/kdls";
import { Badge } from "@/components/ui";

const S = [
  { h:"1. Information We Collect", b:"We collect: (a) information you provide directly — name, email, company, payment details; (b) data generated by using KIKI Agent — signal event data, campaign data, enrichment outputs, usage logs; (c) technical information — IP address, browser type, device identifiers. We do not collect personally identifiable information from your end-customers beyond hashed identifiers (SHA-256 email/phone) used for conversion matching." },
  { h:"2. How We Use Information", b:"We use your information to provide and improve the KIKI Agent platform, process LTV enrichment and fraud detection for your campaigns, send transactional and product communications, conduct security monitoring, and comply with legal obligations. We do not sell your data to third parties or use it for advertising purposes." },
  { h:"3. GDPR & CCPA Rights", b:"If you are a resident of the European Economic Area, United Kingdom, or California, you have rights including: access, rectification, erasure, portability, objection, and restriction of processing. Submit requests to privacy@kiki.ai or via Settings → Privacy → Data Requests. We respond within 72 hours for critical requests and 30 days for standard requests." },
  { h:"4. Data Retention", b:"Signal event data: 24 months. Campaign performance data: account lifetime + 12 months post-closure. Wallet and transaction records: 7 years (financial compliance). LTV model training data: 36 months. You may request deletion of non-financial data at any time." },
  { h:"5. Data Security", b:"All data encrypted at rest (AES-256) and in transit (TLS 1.3). SOC2 Type II certified. Azure Key Vault for secrets management. mTLS between all internal services. Zero-trust RBAC. Quarterly third-party penetration testing. Immutable audit logging." },
  { h:"6. Sub-processors", b:"KIKI Agent uses: Microsoft Azure (infrastructure, EU/US/APAC regions), Stripe (payments, PCI DSS L1), SendGrid (email), OpenAI/Anthropic/Google (AI model inference — no data retained per DPA), DataDog (monitoring). Full list at kiki.ai/sub-processors." },
  { h:"7. Cookies & Tracking", b:"We use strictly necessary cookies for authentication and security. With your consent, we use privacy-preserving analytics (PostHog, no cross-site tracking). We never use advertising or third-party tracking cookies on our platform." },
  { h:"8. Contact & DPA", b:"Privacy Officer: privacy@kiki.ai | KIKI Agent Inc., 350 Mission Street, San Francisco CA 94105 | EU Representative: KIKI Agent EU Ltd., Dublin, Ireland | Data Processing Addendum available at kiki.ai/dpa or on request." },
];

export default function PrivacyPage() {
  return (
    <MarketingLayout>
      <div className="bg-void max-w-[840px] mx-auto" style={{ padding:"clamp(40px,6vw,80px) clamp(16px,4vw,48px)" }}>
        <div className="mb-9">
          <div className="flex items-center gap-2 mb-3.5 flex-wrap">
            <span className="font-mono text-[9px] tracking-[0.18em] text-t4">LEGAL</span>
            <Badge color={K.mint}>GDPR</Badge>
            <Badge color={K.blue}>CCPA</Badge>
            <Badge color={K.teal}>SOC2 TYPE II</Badge>
          </div>
          <h1 className="font-mono font-bold text-t1 tracking-tight mb-2" style={{ fontSize:"clamp(22px,4vw,34px)" }}>Privacy Policy</h1>
          <p className="font-mono text-[11px] text-t3">Last updated: March 20, 2026 · Effective: March 20, 2026</p>
        </div>
        <div className="p-3.5 mb-7 rounded-sm" style={{ background:K.blueT, border:`1px solid ${K.blue}25` }}>
          <p className="font-sans text-[13px] text-t2 leading-[1.7]">This policy describes how KIKI Agent Inc. collects, uses, and protects your information. As a data processor, we handle conversion data strictly according to your instructions.</p>
        </div>
        <div className="prose">
          {S.map((s,i) => (
            <div key={i} className={`mb-7 pb-7 ${i<S.length-1?"border-b border-g800":""}`}>
              <h2 className="font-mono font-bold text-base text-t1 mb-2.5">{s.h}</h2>
              <p className="font-sans text-[13px] text-t2 leading-[1.75]">{s.b}</p>
            </div>
          ))}
        </div>
        <div className="mt-9 p-[18px] bg-g900 border border-g800 rounded-sm">
          <p className="font-mono font-bold text-xs text-t1 mb-1.5">Questions or data requests?</p>
          <p className="font-sans text-[13px] text-t3">Email <span className="text-kblue4">privacy@kiki.ai</span> or use Settings → Privacy → Data Requests in your dashboard.</p>
        </div>
      </div>
    </MarketingLayout>
  );
}
