replicaCount: 1
image:
  repository: kikiagentprodacr.azurecr.io/competitive-intel-service
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3023
resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi
env:
  PORT: "3023"
  NODE_ENV: production
  DATABASE_URL: ""
  KAFKA_BROKERS: "kiki-kafka:9092"
